from pathlib import Path
import re
from docx import Document


SRC = Path(r"C:\Users\肖田泽宇宙最强1234\Desktop\论文\ReCoMER_Method_中英双语_20261004.docx")
OUT = SRC.with_name("ReCoMER_Method_中英双语_20261004_扩展版.docx")


EN = {
    7: """FCCR allows historical evidence to affect modality assessment before the final joint prediction. The implementation first encodes the current utterance and up to three preceding slots with the same modality-specific encoder, so a historical text vector is mapped into the same 192-dimensional space as the current text vector, and the same parameter sharing is used for audio and visual features. For each modality m, the current embedding queries only the valid historical slots through scaled dot-product attention. The history mask and the per-modality availability mask are multiplied before attention; therefore a padded slot, a missing modality, or a history item that does not contain modality m cannot contribute a value vector. This masking is important because the model is intended to work with incomplete multimodal inputs rather than treating zero padding as meaningful evidence. The pooled history summary is then combined with the current representation through the zero-initialized LayerScale parameter γ_m. At initialization, γ_m=0, so the integrated model starts from the current-utterance path and can learn a residual historical correction instead of being forced to trust an uncalibrated memory branch.""",
    9: """The scalar feedback scale γ_m is learned separately for text, audio, and vision and is initialized to zero. The historical summary contains only real, valid historical values; the null candidate used by NCHA contributes a score but no value vector. After the history decision, each updated modality representation is passed to an auxiliary solo head. These heads are not the final classifier. They provide modality-wise evidence that the router can inspect after feedback has changed the representation. The updated representations therefore follow a closed loop: history is selected and admitted first, the current modality states are updated, and the updated states are reassessed before the joint decision. This order prevents the router from assigning a weight to a stale representation that was computed before historical evidence was considered. In the released configuration, the feedback update is applied once. It is not an unbounded recurrent loop, so the computation graph and the number of history reads remain fixed for every utterance.""",
    11: """Here sg denotes stop-gradient. The joint predictor receives the three current modality tokens after feedback and routing. It uses a two-layer six-head Transformer encoder with feed-forward width 576, masked attention, masked mean pooling, and a seven-class output layer for M3ED. The modality mask is carried into both attention and pooling; unavailable tokens do not dilute the representation or receive an artificial uniform contribution. The final predictor can also be evaluated with a controlled modality subset, which is required for the Shapley teacher described in Section 3.3. In the deployed closed-loop path, raw history tokens are omitted from this final head because their information has already entered the current tokens through FCCR. This design avoids counting the same admitted history twice. Consequently, FCCR is a feedback-conditioned forward path: it revises current modality states once and passes those revised states to the joint head, rather than repeatedly modifying predictions until convergence.""",
    13: """SABER estimates modality contribution from both local evidence and shared cross-modal context. Each updated modality embedding is detached and projected by a modality-specific LayerNorm-linear-GELU block to 48 dimensions. A masked mean of the available projections produces a shared context vector. For modality m, the scorer receives the local projection, the shared context, their difference, and a detached evidence vector. In the M3ED classification setting, this evidence vector contains the class probability distribution, maximum probability, normalized entropy, top-two margin, centered-logit scale, disagreement with the available-modality mean prediction, top-class agreement, and a modality-presence flag. Four detached history-state values can additionally expose the history keep probability, the applied admission value, whether history exists, and the mean null-attention mass. Thus the router can distinguish a confident modality from a modality that is confident only before history is rejected. A shared 96-unit scorer maps these features to one contribution estimate μ_m per modality. The final layer is zero-initialized, making the new router start at the uniform base and learn deviations only when the evidence and the Shapley target support them.""",
    14: """The training target is obtained from the current joint predictor rather than from a hand-written modality importance rule. For each training sample, the teacher evaluates all seven nonempty subsets of {T,A,V}. Each subset uses the same feedback-updated current tokens, the same closed-loop history decision, and detached deployment weights; raw history tokens are not appended to the teacher input. For classification, the utility of a subset is the log probability assigned to the ground-truth class, while the empty-set utility is defined as zero. This makes the target sample-specific: a modality is valuable when adding it improves the class probability for that utterance, not merely because it is globally informative on average. The seven evaluations also make the target sensitive to complementary evidence. For example, audio may have a modest individual utility but a large marginal utility after text has already explained the lexical content. Because the expert and router operate on the same class order and utterance alignment, the target can be computed without introducing an auxiliary label vocabulary.""",
    16: """The three-player Shapley value averages marginal utility changes over subsets. For modality m, the target sums the marginal gain obtained when m is added to every subset that does not contain m, weighted by the corresponding factorial coefficient. The result is a three-element vector for each utterance. It is standardized within the sample using the mean and sample standard deviation of the three values before supervising μ. Standardization removes the arbitrary absolute scale of the log probabilities while preserving which modality is relatively more useful for that sample. If all modalities have similar marginal utility, the standardized target is close to uniform; if one modality supplies distinctive evidence, its target becomes positive relative to the others. The teacher is evaluated in inference mode and without gradients. Therefore, the expensive subset evaluations supervise the router but do not back-propagate through the teacher predictions or allow the router loss to reshape the encoders indirectly.""",
    18: """The detached Shapley estimates are converted into bounded deployment weights rather than being used as unrestricted multiplicative gains. The implementation applies a temperature-scaled softmax-like mapping with λ=0.3, followed by nonnegative clipping and renormalization over the available modalities. In the three-modality case, the nominal weights remain in a bounded interval of approximately 0.233 to 0.433. This range prevents a single noisy modality from becoming arbitrarily dominant and also prevents a weak but present modality from being assigned a negative contribution. Missing-modality masks are applied independently of the three-way evidence calculation, so an absent modality receives no token mass even if a numerical scorer produces a finite value. The router inputs and deployment weights are detached from the task loss. As a result, the classification objective trains the prediction path, while the Shapley regression objective trains the router to reproduce the measured utility ordering instead of allowing the router to exploit a shortcut through the classifier.""",
    20: """Equal contribution scores recover uniform weighting, which provides a direct and interpretable control condition for ablation. The bounded route is therefore not a replacement for the current MHnoU predictor; it is a constrained evidence allocation layer placed between modality encoding and joint prediction. Inference uses the saved evidence-router parameters with no subset enumeration. The exact Shapley computation is used only to construct training targets, whereas deployment requires one forward pass through the local scorer. This separation keeps the proposed method computationally practical while retaining a utility-based supervision signal. In the complete bundle, the route is enabled together with closed-loop deployment, the evidence architecture, detached router inputs, Shapley utility, and utility-based history abstention. Older uniform and legacy routes remain useful as structural controls, but they are not the path used for the final ReCoMER bundle.""",
    22: """NCHA separates the selection of historical content from the decision to admit its update. The first attention pass estimates which real historical slots are relevant for each modality. A second pass adds one learned null candidate per modality and lets that candidate compete with valid history. Before feedback, a detached 24-dimensional feature vector summarizes the evidence available to the admission decision. It includes current-utterance entropy, top-two margin, and modality presence for the three modalities; history coverage; current-versus-history prediction divergence and history entropy; speaker-related availability; and the existence and coverage of history. Three text semantic-similarity positions are reserved in the feature layout but are set to zero in the active base configuration. A 24→32→1 calibrator predicts a history-utility logit u. Its sigmoid keep probability is not merely an attention weight: it calibrates the null candidate and also determines a separate utterance-level admission decision.""",
    24: """The current implementation uses T_h=1, β=1, and a hard threshold θ=0.5. Logarithm arguments are clamped at 10⁻⁵ before the keep probability is converted into a null-candidate bias. A high keep probability lowers the relative null score and allows real history to compete normally; a low keep probability raises the null score and makes abstention likely. This construction preserves the original history candidates instead of replacing them with a single scalar gate. The model can therefore select one historical slot more strongly than another while still rejecting the whole historical update when its expected utility is low. During the warm-up and soft-transition periods, the training schedule can expose the encoder to admitted history before the hard decision is activated. The final saved configuration uses the utility-based softmax variant and hard inference semantics, so the reported test prediction has a binary admission outcome.""",
    26: """Here n_m is the learned null embedding, and invalid historical scores are masked before normalization. The null mass reduces the total attention assigned to real history, but it does not create a fake feature vector that is later added to the current state. This distinction makes the abstention mechanism easier to interpret: the null candidate represents a decision not to use history, whereas a real slot represents a concrete previous utterance. The same admission value is also used by the optional memory path, preventing rejected history from bypassing NCHA through a second route. Hard rejection is determined by the keep threshold, not simply by whether the null candidate has the largest softmax probability. During training, the forward value is binary while the backward derivative follows the keep probability through a straight-through estimator. This allows the model to learn a discrete deployment policy without making the history calibrator non-differentiable.""",
    28: """At inference, the binary gate is used directly. If a sample is rejected, the historical residual in Eq. (2) is set to zero for the whole utterance, while the current modality encodings remain available. Because the closed-loop joint head receives no raw history tokens, rejected history cannot re-enter through an auxiliary token path. No history label is required at test time: the decision is based only on detached uncertainty, margin, availability, divergence, and speaker-state features computed from the current input and its available history. This gives NCHA a different role from ordinary attention. Ordinary attention always distributes mass over valid history; NCHA first asks whether any historical update should be admitted at all, then performs content selection conditional on that decision. The resulting gate is especially relevant when a previous utterance is emotionally unrelated, when a modality is missing, or when the history branch is less certain than the current evidence.""",
    30: """Within ReCoMER, cRBEF complements feedback-conditioned history routing with an independent assessment of multimodal evidence. The expert is loaded as a frozen external module and does not share MHnoU encoders or router parameters. It contains a text–audio–visual (TAV) predictor, a separate joint audio–visual (AV) predictor, and a six-input reliability gate. The TAV branch supplies the reference distribution because it covers all available modalities. The AV branch is deliberately independent of text and uses global and local acoustic summaries together with visual features. Its prediction therefore provides a second opinion when the text representation is ambiguous, incomplete, or inconsistent with nonverbal cues. The expert returns the corrected cRBEF distribution, the original TAV distribution, the AV distribution, and the gate value. ReCoMER uses the corrected distribution as the cRBEF peer prediction but keeps the pre-correction TAV output as a reference for the outer local correction.""",
    31: """The TAV predictor consumes the original cRBEF feature contract: a 4096-dimensional text vector, a 1024-dimensional audio vector, and a 342-dimensional visual vector. Audio and vision are projected independently to 256 dimensions and layer-normalized. Binary presence flags mask the projected audio and visual features before they are concatenated with text, giving a 4608-dimensional input. A linear layer reduces this input to 128 dimensions, followed by GELU, dropout with probability 0.2, layer normalization, a seven-class linear head, and a learned scalar logit-temperature parameter implemented through tanh. This branch preserves the original cRBEF representation rather than substituting MHnoU features. Before prediction, present visual vectors are standardized by the stored 342-dimensional mean and scale; absent visual vectors are zero-filled. The explicit presence flags and zero-fill rule ensure that missing vision is distinguishable from a genuine standardized visual observation.""",
    32: """The AV predictor uses its own 1024-dimensional global acoustic summary and four 1024-dimensional local acoustic summaries. The local summaries are flattened to 4096 dimensions. Global audio, local audio, and vision are each projected to 256 dimensions and layer-normalized, then concatenated into a 768-dimensional input to a 128-dimensional classifier with the same GELU, dropout, normalization, and logit-scaling structure as the TAV branch. Although the two branches use related acoustic information, they remain separate predictors with separate parameters. This separation is important for the intended independent-expert interpretation: the AV branch is not a copy of the MHnoU route and does not receive MHnoU history masks. The expert therefore tests whether a nonverbal view supports or contradicts the all-modal reference, while the outer ReCoMER fusion later decides how much of that expert prediction should influence the main model.""",
    33: """Let p^{TAV} and p^{AV} denote the two probability distributions and π the stored training class prior. For each class c, cRBEF forms prior-relative evidence e_c=log p^{AV}_c−log π_c. Positive evidence means that the AV branch supports class c more strongly than its prior frequency would suggest; negative evidence means that the AV branch is less supportive than the prior. The gate does not choose a single branch. Instead, it controls the strength of the complete class-wise evidence vector, allowing several classes to be increased or decreased at once. This is more appropriate than a scalar average because the AV branch can be reliable for one class and uninformative for another. The evidence is added in log-probability space, so the operation remains compatible with normalization and does not depend on an arbitrary probability-scale interpolation.""",
    35: """The gate input s has six components implemented exactly in the expert adapter: the maximum TAV probability, its top-two margin, the maximum AV probability, the strongest prior-relative AV evidence, a binary indicator of top-class agreement, and the unnormalized TAV entropy. A learned linear map from these six statistics to one logit, followed by a sigmoid, produces an utterance-specific gate ρ in (0,1). The first two features describe how decisive the reference branch is; the next two describe the strength of the independent nonverbal view; agreement measures whether the two predictors select the same class; and entropy captures diffuse uncertainty that is not visible from the top class alone. The gate is fitted while the TAV and AV predictors remain fixed. It therefore learns when the AV evidence is useful, rather than jointly changing both experts to explain the training labels.""",
    36: """The gated evidence is added to the TAV log probabilities and normalized over classes to produce p^E=softmax(log p^{TAV}+ρe). When ρ approaches zero, cRBEF reduces to the TAV reference; larger ρ applies a stronger prior-relative AV correction. Because e can be positive or negative, cRBEF can either strengthen or suppress a class. Probability and prior logarithms use a 10⁻⁹ floor, while entropy uses a 10⁻⁸ clamp for numerical stability. The expert is frozen when the outer ReCoMER fusion is fitted: its parameters, gate, class prior, and visual normalization statistics are not updated by the local corrector. In the complete inference object, cRBEF changes the probability evidence supplied to the outer fusion, but it does not directly enter MHnoU's EvidenceRouter and therefore does not silently alter MHnoU's internal modality weights.""",
    38: """The outer fusion uses complete predictions and two reference distributions. The four columns of P are ordered as [p(cRBEF), p(MHnoU), p(TAV), p(no-history MHnoU)]. The first two are the peer predictions that define the baseline; the last two provide anchors for measuring how much the complete predictions changed relative to their internal references. MHnoU and its no-history reference are generated from the same checkpoint, with the latter obtained by zeroing the history masks. The baseline is the equal probability average q=(p(cRBEF)+p(MHnoU))/2. This baseline is deliberately explicit: an unfitted corrector should behave as a transparent two-expert average, so any later gain can be attributed to the bounded local correction rather than to an undocumented weighting rule.""",
    40: """The no-history MHnoU auxiliary logits provide additional relative evidence about the current modalities. The implementation first removes the class-wise mean logit within each modality and then subtracts the mean across available modalities. This produces C with one centered evidence vector for text, audio, and vision. C is not a second prediction and is not fed back into cRBEF; it records which modality is relatively more supportive of a class under the MHnoU checkpoint. The separation between P and C is intentional. P describes the two complete experts and their references, whereas C describes local modal evidence that can explain a disagreement between the experts. The outer network can therefore correct only when the two peer predictions, their reference shifts, and the modal evidence form a consistent pattern.""",
    42: """For each class, the local corrector receives 23 features. Six are the two primary probabilities, their logarithms, the equal-weight baseline probability, and its logarithm. Four global statistics describe the entropy and top-two margin of each primary prediction. Two indicators mark whether each primary assigns the class the highest probability. Eight reference features contain the two reference probabilities, their logarithms, the change from each reference to its corresponding complete prediction, and the L1-normalized versions of those changes. The final three features are the centered relative evidence for T, A, and V. Feature means and standard deviations are fitted only on the fusion fitting set, and standard deviations are clamped to 10⁻⁵. The normalized 23-dimensional vector is clipped to a finite range before entering a shared 23→32→1 GELU network. A separate scalar correction is produced for each class and sample.""",
    44: """The candidate set restricts correction to classes that already have local support. It contains every class whose probability is at least the second-largest probability of either primary expert, together with the class that maximizes the equal-weight baseline; ties at the cutoff are retained. This rule prevents the corrector from transferring mass to an arbitrary low-probability class based on a small numerical fluctuation. Inside the candidate set, the network's bounded residual is exponentiated and used to redistribute the candidate mass. Noncandidate probabilities are preserved at this stage. The correction is therefore local in both senses: it is class-wise rather than a global reweighting of the whole simplex, and it acts only on a small evidence-supported candidate set. The residual scale is bounded by the tanh parameterization and the configured delta scale, which limits the effect of an out-of-distribution feature combination.""",
    46: """The final prediction interpolates between the corrected distribution and the equal-weight baseline. The current implementation uses a correction fraction of 0.25 and stores a selected η in the bundle; η=0 exactly recovers the baseline, while larger η exposes more of the learned correction. During fitting, the corrector is trained with negative log-likelihood, a preservation penalty on samples that the baseline already classifies correctly, and a small squared-residual regularizer. The preservation term discourages unnecessary changes to correct decisions but does not assume that every baseline decision is correct. FIT and CAL are source- and sample-disjoint. The network is fitted at η=1, and η is selected from {0, 0.25, 0.5, 1} using complete-framework weighted F1, with macro F1 and accuracy as tie-breakers. This selection makes the final deployment strength an evaluated hyperparameter rather than an implicit post-hoc choice.""",
    48: """The last correction layer is zero-initialized, so an unfitted LocalCurrentFusion instance is exactly the equal-probability baseline. Candidate mass and noncandidate probabilities are preserved before the final 10⁻⁷ clamp and normalization. This initialization provides a safe fallback when the fitted corrector does not improve the calibration set. It also makes the outer mechanism auditable: setting η to zero, removing the corrector, or loading a zero-initialized corrector produces the same baseline distribution. The outer adjustment operates only on aligned probability outputs and centered evidence; it does not feed cRBEF evidence into MHnoU's internal router. Thus the architecture contains two distinct forms of adaptivity: MHnoU adapts historical admission and modality token weights inside the main predictor, while LocalCurrentFusion adapts the final class probability only after the independent MHnoU and cRBEF opinions have been computed.""",
}


ZH = {
    65: """FCCR 使历史证据在最终联合预测之前参与模态评估。实现首先使用同一个模态专属编码器分别编码当前话语和最多三个历史槽位，因此当前文本与历史文本会被映射到同一个 192 维空间，音频和视觉也采用同样的参数共享关系。对于模态 m，当前表示通过缩放点积注意力查询有效历史槽位。历史掩码与模态级可用性掩码在注意力前相乘，因此填充槽位、缺失模态或不包含模态 m 的历史项都不能提供值向量。这一点避免了把零填充误当成有效证据，使模型能够处理不完整的多模态输入。历史摘要随后通过零初始化的 LayerScale 参数 γ_m 与当前表示相加。初始化时 γ_m=0，整合模型从当前话语路径开始学习，而不是在训练初期被迫信任尚未校准的记忆分支。""",
    67: """反馈缩放系数 γ_m 分别为文本、音频和视觉学习，并全部初始化为零。历史摘要只包含真实且有效的历史值向量；第 3.4 节中的空候选只参与分数竞争，不提供值向量。历史准入完成后，更新后的模态表示分别输入辅助单模态头。这些头不是最终分类器，而是为路由器提供历史反馈之后的模态证据。因此，模型形成一个明确的闭环：先选择并准入历史，再更新当前模态状态，最后基于更新后的状态重新评估模态贡献。这样的顺序避免路由器对尚未吸收历史信息的旧表示分配权重。当前实现只执行一次反馈更新，不是没有边界的循环迭代，因此每个话语的历史读取次数和计算图规模都是固定的。""",
    69: """其中 sg 表示停止梯度传播。联合预测器接收反馈和路由之后的三个当前模态 token，使用两层六头 Transformer、576 维前馈网络、带掩码的注意力、带掩码的均值池化和 M3ED 七分类输出层。模态掩码同时作用于注意力与池化，因此缺失 token 不会稀释联合表示，也不会被人为赋予均匀贡献。联合预测器还可以在受控模态子集上运行，这是第 3.3 节 Shapley 教师构造所必需的。在最终 closed_loop 部署路径中，原始历史 token 不再直接送入联合头，因为历史信息已经通过 FCCR 写回当前 token。这样可以避免同一历史证据被重复计数。因此，FCCR 是一次反馈条件化的前向路径：它先更新当前模态状态，再将更新后的状态交给联合头，而不是不断重复修改预测直到收敛。""",
    71: """SABER 从局部证据和共享跨模态上下文两方面估计模态贡献。每个更新后的模态嵌入先停止梯度传播，再经过模态专属的 LayerNorm、线性层和 GELU 投影到 48 维。对所有可用模态投影做带掩码的均值，得到共享上下文。对于模态 m，评分器接收局部投影、共享上下文、两者之差，以及停止梯度传播的证据向量。在 M3ED 分类设置中，证据向量包括类别概率、最大概率、归一化熵、前两类间隔、中心化 logits 尺度、与可用模态平均预测的差异、最高类别一致性和模态存在标志。还可以加入四个停止梯度的历史状态特征，描述历史保留概率、实际准入值、历史是否存在以及平均空候选注意力质量。这样，路由器能够区分“历史之前就很自信”的模态和“在历史被拒绝之后仍然可靠”的模态。共享的 96 维评分器为每种模态输出一个贡献估计 μ。其最后一层零初始化，使新路由器从均匀分配开始，只在证据和 Shapley 目标都支持时学习偏离。""",
    72: """训练监督并不是来自人为指定的模态重要性，而是来自当前联合预测器对全部七个非空模态子集的评估。对于每个训练样本，教师使用同一组历史反馈更新后的当前 token、同一闭环历史准入决策和停止梯度的部署权重，不再附加原始历史 token。分类任务中，某个子集的效用定义为该子集对真实类别给出的对数概率，空集效用定义为零。由此得到的是样本级目标：某模态只有在当前话语中真正提高真实类别概率时才会获得较高效用，而不会因为它在整个数据集上的平均信息量较大就自动获得高权重。七个子集的计算还能够描述互补性，例如文本已经解释了字面内容后，音频仍可能通过语气提供额外的边际效用。由于教师与路由器使用相同的类别顺序和话语对齐关系，构造目标时不需要额外的标签体系。""",
    74: """三参与者 Shapley 值通过对不含模态 m 的所有子集计算边际效用变化，并按照相应阶乘系数加权平均得到。每个话语最终对应一个三维向量。随后用该样本三个 Shapley 值的均值和样本标准差进行标准化，再监督 μ。标准化去除了对数概率绝对尺度的影响，但保留了模态之间的相对效用排序。当三个模态的边际效用接近时，目标接近均匀；当某一模态提供独特证据时，它相对于其他模态的标准化目标会明显升高。教师在训练时以评估模式运行且不计算梯度。因此，七个子集的昂贵评估只用于监督路由器，不会通过路由损失反向改变教师预测，也不会让编码器为了迎合一个可预测的代理目标而被间接重塑。""",
    76: """停止梯度的 Shapley 估计随后被转换为有界的部署权重，而不是直接作为不受限制的乘法增益。实现使用 λ=0.3 的有界映射，之后进行非负截断，并在可用模态上重新归一化。在三模态完整输入时，三个名义权重约位于 0.233 至 0.433 之间。该范围防止单个噪声模态无限制地主导预测，也防止一个较弱但有效的模态得到负贡献。缺失模态掩码与三模态证据计算相互独立，因此缺失模态即使产生有限的数值评分，也不会获得 token 质量。路由器输入和部署权重都停止梯度传播，使分类目标负责训练预测路径，Shapley 回归目标负责训练路由器复现测得的效用排序，而不是让路由器通过任务损失寻找投机性捷径。""",
    78: """当三个贡献分数相同时，路由结果退化为均匀分配，从而形成直接且易解释的消融条件。因此，有界路由不是替换 MHnoU 主预测器，而是位于模态编码与联合预测之间的受约束证据分配层。训练阶段才需要对七个子集进行精确 Shapley 计算，部署阶段只需经过一次局部评分器前向计算，不再枚举子集。这种训练—部署分离保留了效用监督信号，同时控制了实际推理成本。在完整 ReCoMER 包中，SABER 与 closed_loop、evidence 路由架构、停止梯度输入、Shapley 效用以及 utility_softmax 历史弃权共同启用。旧的 uniform 和 legacy 路径仍作为结构消融与兼容检查保留，但不是最终 ReCoMER 使用的主路径。""",
    80: """NCHA 将历史内容选择和是否接纳历史更新这两个决策分开。第一次注意力计算用于估计每种模态的有效历史槽位，第二次计算为每种模态加入一个可学习的空候选，并让空候选与真实历史竞争。在反馈之前，一个停止梯度传播的 24 维特征向量汇总准入决策所能看到的信息，包括三种模态的熵、前两类间隔和可用性，历史覆盖率，当前与历史预测差异，历史不确定性，说话人相关信息以及历史存在性。在当前基础配置中，三个语义相似度位置保留在特征布局中但被置零。24→32→1 校准器输出历史效用 logit u。其 sigmoid 保留概率不仅校准空候选的分数，还单独决定当前话语是否准入历史更新。""",
    82: """当前实现使用 T_h=1、β=1 和硬阈值 θ=0.5。保留概率转换为空候选偏置之前，对数输入被截断到至少 10⁻⁵。保留概率高时，空候选的相对分数降低，真实历史可以正常竞争；保留概率低时，空候选分数升高，模型更倾向于弃权。该机制保留原有历史候选，而不是把所有历史压缩为一个标量门，因此模型既能在历史被接纳时选择不同槽位，也能在预期效用不足时拒绝整个历史更新。训练初期可以先让编码器看到被准入的历史，再逐步切换到硬决策。最终保存的配置采用 utility_softmax 变体和硬推理语义，因此正式测试时每个话语都会产生明确的二值历史准入结果。""",
    84: """其中 n_m 是可学习的空候选嵌入，无效历史分数在归一化前被掩蔽。空候选质量会降低真实历史值向量获得的总注意力，但不会生成一个随后被加回当前状态的虚假特征。这样，空候选代表“不使用历史”的决策，而真实槽位代表具体的上一轮话语。可选 memory path 也遵守同一个历史准入值，避免被拒绝的历史通过第二条路径绕过 NCHA。硬拒绝由保留概率阈值决定，并不等价于“空候选注意力最大”。训练时前向值为二值，但反向梯度沿保留概率通过直通估计器传播，使模型能够学习离散部署策略，同时保持校准器可训练。""",
    86: """推理时直接使用二值门。若某个样本被拒绝，公式（2）中的历史残差对整个话语被置零，当前模态编码仍然保留。由于 closed_loop 联合头不再接收原始历史 token，被拒绝的历史不能通过额外 token 路径重新进入预测。该决策不需要历史标签，只依赖当前输入及其可用历史上计算出的不确定性、间隔、可用性、预测差异和说话人状态。由此，NCHA 与普通注意力的作用不同：普通注意力总会在有效历史之间分配质量，而 NCHA 先判断“是否应该接纳任何历史更新”，再在接纳之后选择具体内容。这个区别在上一轮话语与当前情绪无关、某一模态缺失或历史分支明显比当前证据更不确定时尤其重要。""",
    88: """在 ReCoMER 中，cRBEF 通过独立评估多模态证据，补充由历史反馈条件化的模态路由。该专家以冻结的外部模块加载，不共享 MHnoU 的编码器或路由器参数。它包含文本—音频—视觉（TAV）预测器、独立的联合音视频（AV）预测器以及接收六项统计量的可靠性门。TAV 分支覆盖全部可用模态，因此提供参考分布；AV 分支不依赖文本，使用全局和局部声学摘要以及视觉特征。这样，当文本表示含糊、不完整或与非语言线索不一致时，AV 分支可以提供独立的第二意见。专家同时返回校正后的 cRBEF 分布、原始 TAV 分布、AV 分布和门值。ReCoMER 将校正后的分布作为 cRBEF 专家意见，并保留校正前 TAV 输出作为外层局部校正的参考。""",
    89: """TAV 预测器严格使用原始 cRBEF 特征契约：4096 维文本向量、1024 维音频向量和 342 维视觉向量。音频与视觉分别线性投影到 256 维并进行层归一化。二值可用性标志先掩蔽音频和视觉投影，再与文本拼接，形成 4608 维输入。随后经过线性降维至 128 维、GELU、0.2 dropout、层归一化、七分类线性层和 tanh 缩放的可学习 logit 温度。该分支保留 cRBEF 原有特征表示，不能用 MHnoU 的特征替代。预测前，可用视觉向量使用保存的 342 维均值和尺度标准化；缺失视觉则填零。显式存在标志和零填充规则使模型能够区分“缺失视觉”和“真实但数值接近零的标准化视觉观察”。""",
    90: """AV 预测器使用独立的 1024 维全局声学摘要和四个 1024 维局部声学摘要，局部摘要展平为 4096 维。全局音频、局部音频和视觉分别投影至 256 维并层归一化，拼接后形成 768 维输入，再进入 128 维隐藏分类网络。该网络沿用 TAV 分支的 GELU、dropout、归一化和 logit 缩放结构。两个分支虽然都使用相关声学信息，但参数完全独立。独立性对于“外部专家”解释十分重要：AV 分支不是 MHnoU 路径的复制，也不接收 MHnoU 的历史掩码。因此，它检验的是非语言视角是否支持或反驳全模态参考，而不是把主模型的历史判断重新包装成一个看似独立的意见。""",
    91: """令 p^{TAV} 和 p^{AV} 表示两个预测分布，π 表示训练类别先验。对于类别 c，cRBEF 计算先验相对证据 e_c=log p^{AV}_c−log π_c。正证据表示 AV 分支对类别 c 的支持强于其在训练数据中的先验频率，负证据则表示支持弱于先验。门值不在两个分支之间进行简单二选一，也不只输出一个全局分数；它控制整个类别级证据向量的作用强度，允许多个类别同时被增强或抑制。这样的 log-probability 计算比直接平均概率更适合表达“某个类别获得额外支持”的关系，也避免了不同分支概率尺度不一致导致的任意插值。""",
    93: """门控输入 s 与代码中的六项统计量一一对应：（1）TAV 最大概率；（2）TAV 前两大概率差；（3）AV 最大概率；（4）所有类别中最大的先验相对 AV 证据；（5）两个分支最高类别是否一致的二值指示；（6）未经归一化的 TAV 熵。六个值经过一个可学习线性映射得到 logit，再通过 sigmoid 得到 0 到 1 之间的话语级门值 ρ。前两项描述参考分支是否决策明确，第三和第四项描述独立非语言证据的强度，第五项衡量两个专家是否协调，第六项捕获仅看最大类别无法反映的分散不确定性。门控拟合期间 TAV 与 AV 预测器保持冻结，因此门只学习“什么时候应该信任 AV 证据”，而不会通过同时改变两个专家来追逐标签。""",
    94: """经过门控的证据加入 TAV 对数概率并归一化，得到 p^E=softmax(log p^{TAV}+ρe)。当 ρ 接近零时，cRBEF 退化为 TAV 参考；当 ρ 较大时，施加更强的先验相对 AV 校正。由于 e 可以为正也可以为负，cRBEF 既能增强类别，也能抑制类别。概率和先验的对数使用 10⁻⁹ 下限，熵计算使用 10⁻⁸ 截断，以避免极小概率造成数值问题。拟合外层 ReCoMER 时，专家参数、可靠性门、类别先验和视觉标准化统计量全部冻结。由此，cRBEF 只改变提供给外层融合的类别概率证据，不直接进入 MHnoU 的 EvidenceRouter，也不会隐式改写 MHnoU 内部的模态权重。""",
    96: """外层融合使用两个完整预测和两个参考分布。P 的四列顺序严格为 [p(cRBEF), p(MHnoU), p(TAV), p(no-history MHnoU)]。前两列是定义基线的两个专家意见，后两列用于衡量完整预测相对于各自内部参考的变化。MHnoU 与无历史参考来自同一个检查点，后者通过将历史掩码全部置零得到。融合基线为 q=(p(cRBEF)+p(MHnoU))/2 的等权概率平均。该基线被显式写入代码：未拟合的校正器必须表现为透明的两专家平均，任何后续提升都应归因于有界局部校正，而不是某个未记录的手工权重。""",
    98: """无历史条件下的 MHnoU 辅助模态 logits 进一步提供当前模态的相对证据。实现先在每个模态内部去除类别均值，再减去可用模态之间的平均值，得到 C 中的文本、音频和视觉中心化证据向量。C 不是第二个预测，也不会反馈给 cRBEF；它表示在同一个 MHnoU 检查点下，各模态相对于其他可用模态更支持哪些类别。将 P 与 C 分开十分重要：P 描述两个完整专家及其参考分布，C 描述能够解释专家分歧的局部模态证据。这样，外层网络只有在完整预测、参考变化和局部模态证据共同形成一致模式时才进行明显校正。""",
    100: """对于每个类别，局部校正器接收 23 个特征。六个基础特征是两个主预测概率、它们的对数、等权基线概率及其对数；四个全局统计量描述两个主预测的熵和前两类间隔；两个指示量表示该类别是否分别是两个主预测的最高类别；八个参考特征包括两个参考概率、其对数、完整预测相对于对应参考的对数概率变化，以及变化的 L1 归一化值；最后三个特征是 T、A、V 的中心化相对证据。特征均值和标准差只在融合拟合集上计算，标准差至少截断到 10⁻⁵。归一化后的 23 维向量先裁剪到有限范围，再输入共享的 23→32→1 GELU 网络，为每个样本和类别生成一个校正值。""",
    102: """候选集合只允许有局部支持的类别参与校正。它包含在任一主专家中概率不低于第二大概率的所有类别，并加入等权基线中概率最大的类别；阈值处的并列类别也会保留。该规则避免校正器因为很小的数值波动，把概率质量转移给原本几乎没有证据的类别。在候选集合内部，网络输出的有界残差经过指数化，用于重新分配候选类别的总概率质量；非候选类别在这一阶段保持不变。因此，校正既是类别级的，也是局部的：它不是对整个概率单纯重新加权，而只在由两个主专家共同支持的候选集合中调整。tanh 参数化和 delta scale 共同限制了异常特征组合可能产生的校正幅度。""",
    104: """最终预测在校正分布和等权基线之间插值。当前实现的 correction_fraction 为 0.25，并在模型包中保存经过选择的 η；η=0 时严格恢复等权基线，η 越大则暴露更多学习到的校正。训练校正器时，目标由负对数似然、对基线原本正确样本的保留惩罚和小权重的残差正则组成。保留项抑制对正确基线决策的无必要改变，但不假设基线没有错误。FIT 与 CAL 在样本和来源上均不重叠。校正器在 η=1 时拟合，再依据完整框架在 CAL 集上的加权 F1 从 {0, 0.25, 0.5, 1} 中选择 η，并用宏平均 F1 和准确率处理并列。因此，最终部署强度是经过评估的超参数，而不是事后凭结果挑选。""",
    106: """校正网络最后一层零初始化，因此尚未拟合的 LocalCurrentFusion 与等权概率基线完全相同。最后的 10⁻⁷ 截断和归一化之前，候选集合总质量与非候选类别概率都被保留。该初始化为拟合失败或外部数据分布变化提供了安全回退，也使外层机制便于审计：令 η=0、移除校正器或加载零初始化校正器都会得到相同的基线分布。外层调整只作用于已经对齐的概率输出和中心化证据，不会把 cRBEF 证据反馈给 MHnoU 内部路由器。因此，模型包含两种相互独立的自适应：MHnoU 在主预测内部自适应历史准入和模态 token 权重，LocalCurrentFusion 则在两个独立专家意见产生之后，自适应地调整最终类别概率。""",
}


def replace_paragraph_text(paragraph, text):
    if not paragraph.runs:
        paragraph.add_run(text)
        return
    paragraph.runs[0].text = text
    for run in paragraph.runs[1:]:
        run.text = ""


def trim_last_sentence(text):
    """Keep the requested expansion concise while preserving sentence boundaries."""
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    if len(parts) <= 2:
        return text
    return " ".join(parts[:-1])


def main():
    doc = Document(SRC)
    # The English target is 2,500--3,000 words for Sections 3.2--3.6.
    # Remove one redundant closing sentence from each expanded English
    # paragraph; all implementation-critical dimensions and operations remain.
    expanded = {**{i: trim_last_sentence(t) for i, t in EN.items()}, **ZH}
    for idx, text in expanded.items():
        replace_paragraph_text(doc.paragraphs[idx], text)
    doc.save(OUT)
    print(OUT)


if __name__ == "__main__":
    main()
